version: "3.8"
services:
  backend:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - PORT=5173
      - ASPNETCORE_URLS=http://0.0.0.0:5173
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
